# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Estate.create!([
  { :name => "Ang Mo Kio", :total => 120, :created_at => "2013-11-26 05:12:35", :updated_at => "2013-11-26 05:12:35" },
  { :name => "Bedok", :total => 506, :created_at => "2013-11-26 05:12:35", :updated_at => "2013-11-26 05:12:35" },
  { :name => "Bishan", :total => 8, :created_at => "2013-11-26 05:12:36", :updated_at => "2013-11-26 05:12:36" },
  { :name => "Bukit Batok", :total => 54, :created_at => "2013-11-26 05:12:36", :updated_at => "2013-11-26 05:12:36" },
  { :name => "Bukit Merah", :total => 133, :created_at => "2013-11-26 05:12:37", :updated_at => "2013-11-26 05:12:37" },
  { :name => "Bukit Panjang", :total => 40, :created_at => "2013-11-26 05:12:37", :updated_at => "2013-11-26 05:12:37" },
  { :name => "Central", :total => 2, :created_at => "2013-11-26 05:12:37", :updated_at => "2013-11-26 05:12:37" },
  { :name => "Choa Chu Kang", :total => 768, :created_at => "2013-11-26 05:12:37", :updated_at => "2013-11-26 05:12:37" },
  { :name => "Clementi", :total => 269, :created_at => "2013-11-26 05:12:38", :updated_at => "2013-11-26 05:12:38" },
  { :name => "Geylang", :total => 11, :created_at => "2013-11-26 05:12:38", :updated_at => "2013-11-26 05:12:38" },
  { :name => "Hougang", :total => 43, :created_at => "2013-11-26 05:12:38", :updated_at => "2013-11-26 05:12:38" },
  { :name => "Jurong East", :total => 22, :created_at => "2013-11-26 05:12:38", :updated_at => "2013-11-26 05:12:38" },
  { :name => "Jurong West", :total => 153, :created_at => "2013-11-26 05:12:39", :updated_at => "2013-11-26 05:12:39" },
  { :name => "Kallang/Whampoa", :total => 558, :created_at => "2013-11-26 05:12:39", :updated_at => "2013-11-26 05:12:39" },
  { :name => "Pasir Ris", :total => 132, :created_at => "2013-11-26 05:12:40", :updated_at => "2013-11-26 05:12:40" },
  { :name => "Punggol", :total => 394, :created_at => "2013-11-26 05:12:40", :updated_at => "2013-11-26 05:12:40" },
  { :name => "Queenstown", :total => 35, :created_at => "2013-11-26 05:12:40", :updated_at => "2013-11-26 05:12:40" },
  { :name => "Sembawang", :total => 15, :created_at => "2013-11-26 05:12:41", :updated_at => "2013-11-26 05:12:41" },
  { :name => "Sengkang", :total => 176, :created_at => "2013-11-26 05:12:41", :updated_at => "2013-11-26 05:12:41" },
  { :name => "Serangoon", :total => 4, :created_at => "2013-11-26 05:12:41", :updated_at => "2013-11-26 05:12:41" },
  { :name => "Tampines", :total => 117, :created_at => "2013-11-26 05:12:42", :updated_at => "2013-11-26 05:12:42" },
  { :name => "Toa Payoh", :total => 11, :created_at => "2013-11-26 05:12:42", :updated_at => "2013-11-26 05:12:42" },
  { :name => "Woodlands", :total => 218, :created_at => "2013-11-26 05:12:42", :updated_at => "2013-11-26 05:12:42" },
  { :name => "Yishun", :total => 184, :created_at => "2013-11-26 05:12:43", :updated_at => "2013-11-26 05:12:43" }
])


